#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>
# Licensed under The GNU Public License Version 2 (or later)

import jinja2
import math
import matplotlib.pyplot as pl
import numpy as np
import scipy.optimize as op
import scipy.interpolate

def skizze_d(T):
    f = np.linspace(1, 1e4, 1e4)
    v = np.sqrt(1 + 4 * np.pi**2 * 100e3**2 * 100e-9**2 * f**2)

    pl.loglog(f, v)
    pl.xlabel(r"$f$/ Hz")
    pl.ylabel(r"$v$")
    pl.grid(True)
    pl.savefig("5_6-D.pdf")
    pl.clf()

def verstaerker_part(T, filename, color, label, table_key, f_T_key, f_grenz_key):
    # Daten einlesen.
    data = np.genfromtxt(filename)

    # Daten mappen.
    f = data[:, 0]
    uin = data[:, 1]
    uout = data[:, 2]

    # Weitere Daten ausrechnen.
    v = uout/uin

    # Messwerte plotten.
    pl.loglog(f, v, label=label, linestyle="none", marker="o", color=color)

    # Messwerte interpolieren.
    inter = scipy.interpolate.interp1d(f, v, kind='quadratic')
    x = np.linspace(np.min(f), np.max(f), 100)
    y = inter(x)
    pl.loglog(x, y, color=color)

    # Transitfrequenz bestimmen.
    f_T = scipy.optimize.brentq(lambda x: inter(x) - 1, np.min(f), np.max(f))
    pl.loglog(f_T, inter(f_T), linestyle="none", marker="d", color=color)

    # Grenzfrequenz bestimmen.
    def grenz(x):
        return inter(x) - np.max(v) / np.sqrt(2)
    f_grenz = scipy.optimize.brentq(grenz, np.min(f), np.max(f))
    pl.loglog(f_grenz , inter(f_grenz ), linestyle="none", marker="*", color=color, markersize=10)

    # Daten exporieren.
    T[table_key] = np.column_stack([f, uin, uout, np.round(v, 3)])
    T[f_T_key] = g(f_T)
    T[f_grenz_key] = g(f_grenz)

def verstaerker(T):
    verstaerker_part(T, "Verstaerker-11.txt", "red", "$V = 11$",
                     "table_verstaerker_11", "f_T_11", "f_grenz_11")
    verstaerker_part(T, "Verstaerker-101.txt", "green", "$V = 101$",
                     "table_verstaerker_101", "f_T_101", "f_grenz_101")
    verstaerker_part(T, "Verstaerker-2.txt", "blue", "$V = 2$",
                     "table_verstaerker_2", "f_T_2", "f_grenz_2")
    verstaerker_part(T, "Verstaerker-Kondensator.txt", "purple",
                     "$V = 11$, Kondensator", "table_verstaerker_c", "f_T_c",
                     "f_grenz_c")

    pl.xlabel(r"$f / \mathrm{Hz}$")
    pl.ylabel(r"$v$")
    pl.grid(True)
    pl.legend(loc="best")
    pl.savefig("Plot-Verstaerker.pdf")
    pl.clf()

def addierer(T):
    x = np.linspace(0, 2*np.pi, 1000)

    y1 = np.sin(x)
    y2 = 1/2 * np.sin(2*x)
    y3 = 1/3 * np.sin(3*x)

    y = 2 / np.pi * (y1 + y2 + y3)

    pl.plot(x, y1, label=r"$\sin(x)$")
    pl.plot(x, y2, label=r"$\sin(2x)$")
    pl.plot(x, y3, label=r"$\sin(3x)$")
    pl.plot(x, y, label="Summe", linewidth=3, color="black")
    pl.xlabel("$x$")
    pl.ylabel("$f(t)$")
    pl.grid(True)
    pl.legend(loc="best")
    pl.savefig("Plot-Saegezahn.pdf")
    pl.clf()

def g(value, error=None, digits=3):
    if error is None:
        return ("{:."+str(digits)+"g}").format(value)
    else:
        value_log = int(math.floor(math.log(np.abs(value), 10)))
        error_log = int(math.floor(math.log(np.abs(error), 10)))

        difference = value_log - error_log
        exp = 0

        if difference >= 0:
            value_dis = value * 10**(difference - value_log)
            error_dis = error * 10**(- error_log)
            exp = error_log
        else:
            value_dis = value * 10**(- value_log)
            error_dis = error * 10**(difference - error_log)
            exp = value_log

        format_string = "{:."+str(digits-1)+"f} +- {:."+str(digits-1)+"f} e{:+d}"
        return format_string.format(value_dis, error_dis, exp)

def render_template(T):
    # Setting up Jinja
    env = jinja2.Environment(
        "%<", ">%",
        "<<", ">>",
        "%§", "§%",
        loader=jinja2.FileSystemLoader(".")
    )
    template3 = env.get_template("Template_5.tex")

    # Rendering LaTeX document with values.
    with open("physik313-5-Ueding_Lemmer.tex", "w") as f:
        f.write(template3.render(**T))

def main():
    T = {}

    skizze_d(T)
    verstaerker(T)
    addierer(T)

    render_template(T)

if __name__ == "__main__":
    main()
